### ISSUE TITLE
Paper results : in raw frames ?

### ISSUE THREAD

**Issue by Jogima-cyber** [suyoung-lee/Episodic-Backward-Update#1]
I'm studying your paper in a quest for more sample efficient RL agents and I have a hard time comparing results. In _Human-level control through deep reinforcement
learning_ are results in raw frames or did they divide their raw frames by 4 because of repeating 4 times the actions? Same question for your paper _Sample-Efficient Deep Reinforcement Learning via
Episodic Backward Update_.

**Comment by suyoung-lee** [comment]
Our setting is &nbsp;excatly the same as Human-level control through deep reinforcement learning.
Both work regard 1 timestep as 4 raw frames due to both frameskip and train 200M frames (=50M steps) in total.&nbsp;

Here is a helpful summary of the frameskip and action repeat.&nbsp;
https://danieltakeshi.github.io/2016/11/25/frame-skipping-and-preprocessing-for-deep-q-networks-on-atari-2600-games/ https://danieltakeshi.github.io/2016/11/25/frame-skipping-and-preprocessing-for-deep-q-networks-on-atari-2600-games/


Action repeat is a technique applied separately from frame skip.



-----Original Message-----
From: "Joseph Amigo" ***@***.***&gt;
To: "suyoung-lee/Episodic-Backward-Update" ***@***.***&gt;;
Cc: "Subscribed" ***@***.***&gt;;
Sent: 2021-08-14 (Sa) 17:46:10 (UTC+09:00)
Subject: [suyoung-lee/Episodic-Backward-Update] Paper results : in raw frames ? (#1)


I'm studying your paper in a quest for more sample efficient RL agents and I have a hard time comparing results. In Human-level control through deep reinforcement&nbsp;learning are results in raw frames or did they divide their raw frames by 4 because of repeating 4 times the actions? Same question for your paper Sample-Efficient Deep Reinforcement Learning via&nbsp;Episodic Backward Update.
